### ISSUE TITLE
Doesn't build with ARMC6.13

### ISSUE THREAD

**Issue by MarceloSalazar** [ARMmbed/mbed-os-example-atecc608a#31]
Testing Mbed OS 5.15 branch: mbed-os-5.15 and seeing link errors:
```
>mbed compile -t ARM -m K64F -v
[mbed] Working path "C:\OOB\mbed-os-example-atecc608a" (program)
[mbed] Exec "c:\python27\python.exe -u C:\OOB\mbed-os-example-atecc608a\mbed-os\tools\make.py -t ARM -m K64F --source . --build .\BUILD\K64F\ARM -v" in "C:\OOB\mbed-os-example-atecc608a"
Building project mbed-os-example-atecc608a (K64F, ARMC6)
Scan: mbed-os-example-atecc608a
Macros: -DTARGET_PSA -DCOMPONENT_SD=1 -DDEVICE_EMAC=1 -D__MBED__=1 -DDEVICE_USBDEVICE=1 -D__FPU_PRESENT=1 -DTARGET_Freescale -DDEVICE_PORTINOUT=1 -DTARGET_RTOS_M4_M7 -DTARGET_NAME=K64F -DDEVICE_RTC=1 -DCOMPONENT_PSA_SRV_EMUL=1 -DDEVICE_SERIAL_ASYNCH=1 -D__CMSIS_RTOS -DTOOLCHAIN_ARMC6 -DFSL_RTOS_MBED -DTARGET_KPSDK_MCUS -DDEVICE_WATCHDOG=1 -DDEVICE_USTICKER=1 -DDEVICE_CRC=1 -DDEVICE_RESET_REASON=1 -DTARGET_CORTEX_M -DTARGET_KSDK2_MCUS -DTARGET_LIKE_CORTEX_M4 -DDEVICE_ANALOGOUT=1 -DTARGET_M4 -DTARGET_K64F -DCOMPONENT_PSA_SRV_IMPL=1 -DDEVICE_SPI_ASYNCH=1 -DMBED_BUILD_TIMESTAMP=1575977212.96 -DDEVICE_PWMOUT=1 -DCOMPONENT_FLASHIAP=1 -DMBED_TICKLESS -DDEVICE_INTERRUPTIN=1 -DTARGET_Freescale_EMAC -DTARGET_CORTEX -DDEVICE_I2C=1 -DDEVICE_PORTOUT=1 -DDEVICE_I2CSLAVE=1 -D__CORTEX_M4 -DDEVICE_STDIO_MESSAGES=1 -DCPU_MK64FN1M0VMD12 -DTARGET_LIKE_MBED -DTARGET_FF_ARDUINO -DTARGET_KPSDK_CODE -DTARGET_RELEASE -DDEVICE_LPTICKER=1 -DCOMPONENT_NSPE=1 -DDEVICE_SERIAL_FC=1 -DMBED_SPLIT_HEAP -DDEVICE_TRNG=1 -D__MBED_CMSIS_RTOS_CM -DDEVICE_SLEEP=1 -DTARGET_FRDM -DTARGET_MCUXpresso_MCUS -DDEVICE_SPI=1 -DTOOLCHAIN_ARM_STD -DDEVICE_SPISLAVE=1 -DDEVICE_ANALOGIN=1 -DDEVICE_SERIAL=1 -DDEVICE_FLASH=1 -DDEVICE_PORTIN=1 -DTOOLCHAIN_ARM -DTARGET_MCU_K64F -DARM_MATH_CM4
Link: mbed-os-example-atecc608a
Link: C:\Program Files\ARMCompiler6.13\bin\armlink --via .\BUILD\K64F\ARM\.link_options.txt
[DEBUG] Return: 1
[Warning] @0,0: L3912W: Option 'legacyalign' is deprecated.
[Error] @0,0: L6218E: Undefined symbol atcab_printbin_label (referred from BUILD/K64F/ARM/atecc608a/main.o).
[Error] @0,0: L6218E: Undefined symbol atcab_printbin_sp (referred from BUILD/K64F/ARM/atecc608a/main.o).
[Error] @0,0: L6218E: Undefined symbol mbedtls_psa_register_se_key (referred from BUILD/K64F/ARM/atecc608a/main.o).
[Error] @0,0: L6218E: Undefined symbol psa_register_se_driver (referred from BUILD/K64F/ARM/atecc608a/main.o).
[Error] @0,0: L6218E: Undefined symbol psa_set_key_slot_number (referred from BUILD/K64F/ARM/atecc608a/main.o).
[DEBUG] Errors: Warning: L3912W: Option 'legacyalign' is deprecated.
[DEBUG] Errors: Error: L6218E: Undefined symbol atcab_printbin_label (referred from BUILD/K64F/ARM/atecc608a/main.o).
[DEBUG] Errors: Error: L6218E: Undefined symbol atcab_printbin_sp (referred from BUILD/K64F/ARM/atecc608a/main.o).
[DEBUG] Errors: Error: L6218E: Undefined symbol mbedtls_psa_register_se_key (referred from BUILD/K64F/ARM/atecc608a/main.o).
[DEBUG] Errors: Error: L6218E: Undefined symbol psa_register_se_driver (referred from BUILD/K64F/ARM/atecc608a/main.o).
[DEBUG] Errors: Error: L6218E: Undefined symbol psa_set_key_slot_number (referred from BUILD/K64F/ARM/atecc608a/main.o).
[DEBUG] Errors: Finished: 0 information, 1 warning and 5 error messages.
Traceback (most recent call last):
  File "C:\OOB\mbed-os-example-atecc608a\mbed-os\tools\make.py", line 78, in wrapped_build_project
    *args, **kwargs
  File "C:\OOB\mbed-os-example-atecc608a\mbed-os\tools\build_api.py", line 598, in build_project
    res = toolchain.link_program(resources, build_path, name)
  File "C:\OOB\mbed-os-example-atecc608a\mbed-os\tools\toolchains\mbed_toolchain.py", line 773, in link_program
    self.link(elf, objects, libraries, lib_dirs, linker_script)
  File "C:\OOB\mbed-os-example-atecc608a\mbed-os\tools\toolchains\arm.py", line 387, in link
    self.default_cmd(cmd)
  File "C:\OOB\mbed-os-example-atecc608a\mbed-os\tools\toolchains\mbed_toolchain.py", line 825, in default_cmd
    raise ToolException(stderr)
ToolException: Warning: L3912W: Option 'legacyalign' is deprecated.
Error: L6218E: Undefined symbol atcab_printbin_label (referred from BUILD/K64F/ARM/atecc608a/main.o).
Error: L6218E: Undefined symbol atcab_printbin_sp (referred from BUILD/K64F/ARM/atecc608a/main.o).
Error: L6218E: Undefined symbol mbedtls_psa_register_se_key (referred from BUILD/K64F/ARM/atecc608a/main.o).
Error: L6218E: Undefined symbol psa_register_se_driver (referred from BUILD/K64F/ARM/atecc608a/main.o).
Error: L6218E: Undefined symbol psa_set_key_slot_number (referred from BUILD/K64F/ARM/atecc608a/main.o).
Finished: 0 information, 1 warning and 5 error messages.

[mbed] ERROR: "c:\python27\python.exe" returned error.
       Code: 1
       Path: "C:\OOB\mbed-os-example-atecc608a"
       Command: "c:\python27\python.exe -u C:\OOB\mbed-os-example-atecc608a\mbed-os\tools\make.py -t ARM -m K64F --source . --build .\BUILD\K64F\ARM -v"
       Tip: You could retry the last command with "-v" flag for verbose output
---
```

AC6.13:
```
>armclang --version
Product: ARM Compiler 6.13 Professional
Component: ARM Compiler 6.13
Tool: armclang [5d895a00]
```

@Patater @adbridge

**Comment by MarceloSalazar** [comment]
I tested a fix as PR https://github.com/ARMmbed/mbed-os-example-atecc608a/pull/32 and confirm it compiles ok with AC 6.13.
